version: "3.5"

services:
  # ELK
  elasticsearch:
    image: library/elasticsearch:6.5.0
    volumes:
      # for persistent data
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - master
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G

  kibana:
    image: library/kibana:6.5.0
    ports:
      - 5601:5601
    networks:
      - master
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure
    labels:
      - "traefik.backend=kibana"
      - "traefik.docker.network=${network_name:-masternetwork}"
      - "traefik.frontend.rule=Host:kibana.${BASE_URL:-localhost}" # add another rule with ";Host:host"
      - "traefik.enable=true"
      - "traefik.port=5601"

  # FTP server
  ftp:
    image: stilliard/pure-ftpd:hardened
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "./ftpdata:/home/username/"
      - "./passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
    restart: always

networks:
  # Network mostly needed for swarm
  # Set to bridge to test locally and have ports be outside accessible
  master:
    name: "${network_name:-masternetwork}"
    driver: overlay
